export const Users = [
    {
        id:1,
        profilePicture: "assets/people/landon.jpg",
        username: "Landon Conover",
    },
    {
        id:2,
        profilePicture: "assets/people/thor.png",
        username: "Thor Anderson",
    },
    {
        id:3,
        profilePicture: "assets/people/paul.jpg",
        username: "Paul Cheney",
    },
    {
        id:4,
        profilePicture: "assets/people/andrew.jpg",
        username: "Andrew Peterson",
    },
    {
        id:5,
        profilePicture: "assets/people/danila.jpg",
        username: "Danila Lubov",
    },
    {
        id:6,
        profilePicture: "assets/people/raine.jpg",
        username: "Raine Petersen",
    },
    {
        id:7,
        profilePicture: "assets/people/moe.jpg",
        username: "Moe Peterson",
    },
    {
        id:8,
        profilePicture: "assets/people/lavina.jpg",
        username: "Lavina Paige",
    },
    {
        id:9,
        profilePicture: "assets/people/echo.jpg",
        username: "Echo Crawford",
    },
    {
        id:10,
        profilePicture: "assets/people/zilla.jpg",
        username: "Zilla Bowie",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "I am currently traveling in San Diego right now and my hotel has a gym. This reminded me how coding is like going to the gym. You can't look or code like me if you don't follow this philosophy.",
        photo: "assets/asia-photo1.jpg",
        date: "Just now",
        userId: 1,
        likes: 13,
        comments: 5,
    },
    {
        id: 2,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo3.jpg",
        date: "10 mins ago",
        userId: 2,
        likes: 13,
        comments: 5,
    },
    {
        id: 3,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo4.jpg",
        date: "30 mins ago",
        userId: 3,
        likes: 13,
        comments: 5,
    },
    {
        id: 4,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo5.jpg",
        date: "45 mins ago",
        userId: 4,
        likes: 13,
        comments: 5,
    },
    {
        id: 5,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo6.jpg",
        date: "1 hour ago",
        userId: 5,
        likes: 13,
        comments: 5,
    },
    {
        id: 6,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo7.jpg",
        date: "2 hours ago",
        userId: 6,
        likes: 13,
        comments: 5,
    },
    {
        id: 7,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo8.jpg",
        date: "3 hours ago",
        userId: 7,
        likes: 13,
        comments: 5,
    },
    {
        id: 8,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo9.jpg",
        date: "4 hours ago",
        userId: 8,
        likes: 13,
        comments: 5,
    },
    {
        id: 9,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo10.jpg",
        date: "5 hours ago",
        userId: 9,
        likes: 13,
        comments: 5,
    },
    {
        id: 10,
        desc: "Coding is like going to the gym.",
        photo: "assets/asia-photo1.jpg",
        date: "6 hours ago",
        userId: 10,
        likes: 13,
        comments: 5,
    },
];